### PR TITLE
Don't send response on response webhook

### PR DESCRIPTION
**Pull request by nrempel**

### CODE REVIEW

**Comment by swcurran** [comment]
Should we be turning this off or the auto-handling?  Maybe in this case auto-handling is OK, but I don't think it should be encouraged too much.  The controller should handle most things.

AFAIK auto-xxx is good for demos, but not for production.

**Comment by nrempel** [comment]
In this case, the logic to send the (duplicate) response message is triggered when the webhook indicating that the response has been sent is received. So it's both or nothing if we turn off the auto flag. We want to avoid too many code changes to the fragile implementation, so this should hopefully do what we need without changing much.

I don't think there is anything wrong with auto-responding to messages in production if we always want accept the connection.

**Comment by swcurran** [comment]
Sounds good.  I'm fine with the minor change for now. I'm just saying in future we should have as a guideline (as they say in Pirates of the Caribbean) that we implement controller's without auto-xxx configs.  We don't want to be over-reliant on automated ACA-Py behaviour that should be handled by the controller.  IMHO Better to have an easily configured controller that is explicit about what it is doing.

**Comment by esune** [comment]
> 
> 
> Sounds good. I'm fine with the minor change for now. I'm just saying in future we should have as a guideline (as they say in Pirates of the Caribbean) that we implement controller's without auto-xxx configs. We don't want to be over-reliant on automated ACA-Py behaviour that should be handled by the controller. IMHO Better to have an easily configured controller that is explicit about what it is doing.

+1 to adding guidelines/docs about this that are easy to get to for someone starting with a new agent-controller setup, I can see how this could happen again in new projects.

Other projects we are running have the `--auto-accept-request` flag enabled as well, but the controller is likely not sending duplicates like in this case.

**Comment by nrempel** [comment]
Ok, I've done some thorough testing in our dev environment for this and I believe this change fixes the issue we're seeing with the Streetcred agent.

I also don't see any errors in the Streetcred logs like we saw previously.

**Pull request merged**
